# Generated by Django 5.0.6 on 2025-09-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MpesaReceipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='recipient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
